language: node_js

node_js:
  - "node"

cache:
  directories:
    - "node_modules"

install:
  - npm install
  
script:
  - npm run test
  - npm run build

after_success:
  # - npm run cover

deploy:
  provider: pages
  keep-history: true
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master